### ISSUE TITLE
[Bug] AttributeError Octolapse on running script

### ISSUE THREAD

**Issue by javl** [cp2004/Octoprint-Upgrade-To-Py3#23] opened 2020-09-20 10:33 UTC
**Describe the bug**
When running the script I get the following AttributeError. I can still continue the installation though.
Seems to be caused by something related to octolapse, but as this is a popular plugin it might be worth to check what is going on?

**Script output**
```
Detecting system info...
OctoPi version: 0.17.0
Getting OctoPrint version...
OctoPrint version: 1.4.2
Reading installed plugins...
No handlers could be found for logger "octoprint.plugin.core"
2020-09-20 11:27:33,148 - octolapse.__init__ - INFO - Release mode detected.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1676, in shutdown
    h.close()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/logging/handlers.py", line 32, in close
    self._executor.shutdown(wait=True)
AttributeError: 'OctolapseConsoleHandler' object has no attribute '_executor'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1676, in shutdown
    h.close()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/logging/handlers.py", line 32, in close
    self._executor.shutdown(wait=True)
AttributeError: 'OctolapseConsoleHandler' object has no attribute '_executor'

Plugins installed
- Floating Navbar
- HeaterTimeout
- PSU Control
- Progress Title
- Gcodebar Plugin
- TemperatureFailsafe
- Octolapse
- Bed Visualizer
- Themeify
- Navbar Temperature Plugin
If you think there is something missing from here, please check the list of plugins in Octoprint
Press [enter] to continue or ctrl-c to quit

```

**Script version**
v2.1.7

**OctoPrint Version**
OctoPrint 1.4.2

**Relevant plugins that may have caused errors**
The error mentions Octolapse.

**Comment by cp2004** [comment] 2020-09-20 11:08
Duplicate of #6 

Do not worry, no functional impact. I have reported it to the OctoLapse author.

**Closed by cp2004** 2020-09-20 11:08 UTC
Labels: bug
